MyCompanyMyProjectTestBundle:
    resource: "@MyCompanyMyProjectTestBundle/Resources/config/routing.yml"
    prefix:   /
    
MyCompanyMyProjectSysBundle:
    resource: "@MyCompanyMyProjectSysBundle/Resources/config/routing.yml"
    prefix:   /  
    
MyCompanyMyProjectAppBundle:
    resource: "@MyCompanyMyProjectAppBundle/Resources/config/routing.yml"
    prefix:   /     


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
