# app/config/security.yml
security:
    firewalls:        
       secured_area:
           pattern:    ^/
           anonymous: ~
           http_basic:
             realm: "Secured Demo Area"
        #main:
         #   switch_user: true
          #  pattern:    ^/
          #  anonymous: ~
            #provider: user_db
            #http_basic:
            #    realm: "Secured Demo Area"
            #    provider: in_memory
            #form_login: ~
            #logout:
            #    path:   /logout
            #    target: /
                
    access_control:       
        #- { path: ^/admin, roles: ROLE_ADMIN }
      

    providers:
        in_memory:
            users:
                ryan:  { password: ryanpass, roles: 'ROLE_USER' }
                admin: { password: kitten, roles: 'ROLE_ADMIN' }
            #entity: {class: MyCompanyTaskBundle:User, property: username } 
                
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext