<?php
	// Entity class generated automatically by MDA process
	namespace MyCompany\MyProject\AppBundle\Entity;

	use Doctrine\ORM\Mapping as ORM;
	use JMS\SecurityExtraBundle\Annotation\Secure;
	use Symfony\Component\Validator\Constraints as Assert;
	use Symfony\Bridge\Doctrine\Validator\Constraints as DoctrineAssert;
	use Doctrine\Common\Collections\ArrayCollection;

	/**
 	* MyCompany\MyProject\AppBundle\Entity\FraudeTypologie
 	*
 	* @ORM\Table(name="fraude_typologie")
 	* @ORM\Entity(repositoryClass="MyCompany\MyProject\AppBundle\Repository\FraudeTypologieRepository")
	* */
   	class FraudeTypologie
	{	
		// MDA Generated variables (used for internal entity management)
		private $error = '';
		public $validName = true;
		public $validThreshold = true;

		/**
     	* @var bigint $id
     	*
     	* @ORM\Column(name="id", type="bigint", nullable=false)
     	* @ORM\Id
     	* @ORM\GeneratedValue(strategy="IDENTITY")
     	*/
    	private $id;
		/**
     	* @var string $name
     	*
     	* @ORM\Column(name="name", type="string" ,length=50,nullable=false)
     	*/
    	private $name;
		/**
     	* @var decimal $threshold
     	*
     	* @ORM\Column(name="threshold", type="decimal",precision=2 ,nullable=false)
     	*/
    	private $threshold;
		public function __construct()
    	{
		}
	
		/**
     	* Get id
     	*
     	* @return bigint 
     	*/
    	public function getId()
    	{
        	return $this->id;
    	}
    	public function setId($id)
    	{
        	$this->id = $id;
    	}
		/**
     	* Get Name 
		* by Id (automatic get generated by Symfony
     	*        when form display choice list)
     	* @return string
     	*/		
		public function __toString() {
			return $this->getName();
		}
		/**
     	* Get threshold
     	*
     	* @return decimal 
     	*/
     	public function getThreshold() {
       		return $this->threshold;
     	}
		/**
     	* Get name
     	*
     	* @return string 
     	*/
     	public function getName() {
       		return $this->name;
     	}
		/**
     	* Set name
     	*
     	* @param string $name
     	*/ 
     	public function setName($name) {
			$this->name=$name;  
  	 	}	
		/**
     	* Set threshold
     	*
     	* @param decimal $threshold
     	*/ 
     	public function setThreshold($threshold) {
			$this->threshold=$threshold;  
  	 	}	
		// Object validation function (see Resources/config/validation.yml)
		public function isNameValid() {
			$rc = true; $errorMgr = $this; $errorMsg = ''; 
			$this->validName = true;
			/*==============START OF VALIDATION RULE====================*/ 
			
			/*==============END OF VALIDATION RULE======================*/
			if(!$rc) {
				$errorMgr->setError($errorMsg);
				$this->validName = false;
				return $rc;
			}
		}
		// Object validation function (see Resources/config/validation.yml)
		public function isThresholdValid() {
			$rc = true; $errorMgr = $this; $errorMsg = ''; 
			$this->validThreshold = true;
			/*==============START OF VALIDATION RULE====================*/ 
			
			/*==============END OF VALIDATION RULE======================*/
			if(!$rc) {
				$errorMgr->setError($errorMsg);
				$this->validThreshold = false;
				return $rc;
			}
		}
		public function setError($error) {
			$this->error = $error;
		}
		public function getError() {
			return $this->error;
		}
   }
?>
