<?php
	// Entity class generated automatically by MDA process
	namespace MyCompany\MyProject\AppBundle\Entity;

	use Doctrine\ORM\Mapping as ORM;
	use JMS\SecurityExtraBundle\Annotation\Secure;
	use Symfony\Component\Validator\Constraints as Assert;
	use Symfony\Bridge\Doctrine\Validator\Constraints as DoctrineAssert;
	use Doctrine\Common\Collections\ArrayCollection;

	/**
 	* MyCompany\MyProject\AppBundle\Entity\FraudeEvenement
 	*
 	* @ORM\Table(name="fraude_evenement")
 	* @ORM\Entity(repositoryClass="MyCompany\MyProject\AppBundle\Repository\FraudeEvenementRepository")
	* */
   	class FraudeEvenement
	{	
		// MDA Generated variables (used for internal entity management)
		private $error = '';
		public $validDateEvt = true;
		public $validDescription = true;
		public $validMontant = true;
		public $validSaisie = true;
		public $validTitre = true;
		public $validToString = true;
		public $validTypologie = true;

		/**
     	* @var bigint $id
     	*
     	* @ORM\Column(name="id", type="bigint", nullable=false)
     	* @ORM\Id
     	* @ORM\GeneratedValue(strategy="IDENTITY")
     	*/
    	private $id;
		/**
     	* @var datetime $dateEvt
     	*
     	* @ORM\Column(name="dateEvt", type="datetime" ,nullable=false)
     	*/
    	private $dateEvt;
		/**
     	* @var string $description
     	*
     	* @ORM\Column(name="description", type="string" ,length=400,nullable=false)
     	*/
    	private $description;
		/**
     	* @var decimal $montant
     	*
     	* @ORM\Column(name="montant", type="decimal",precision=2 ,nullable=false)
     	*/
    	private $montant;
		/**
     	* @var Saisie
		*
     	* @ORM\ManyToOne(targetEntity="FraudeSaisie", inversedBy="evenement")
     	* @ORM\JoinColumns({
     	* @ORM\JoinColumn(name="saisie_id", referencedColumnName="id", unique=true)
     	* })
		*/
		private $saisie;		
		/**
     	* @var string $titre
     	*
     	* @ORM\Column(name="titre", type="string" ,length=40,nullable=false)
     	*/
    	private $titre;
		/**
     	* @var Typologie
     	* @ORM\ManyToOne(targetEntity="FraudeTypologie")
     	* @ORM\JoinColumns({
     	* @ORM\JoinColumn(name="typologie_id", referencedColumnName="id", unique=true)
     	* })
		*/
		private $typologie;		
		public function __construct()
    	{
		}
	
		/**
     	* Get id
     	*
     	* @return bigint 
     	*/
    	public function getId()
    	{
        	return $this->id;
    	}
    	public function setId($id)
    	{
        	$this->id = $id;
    	}
		/**
     	* Get Name 
		* by Id (automatic get generated by Symfony
     	*        when form display choice list)
     	* @return string
     	*/		
		public function __toString() {
			$string = "Event". $this->getId();
			if(isset($string)) return $string;			
		}
		/**
     	* Get montant
     	*
     	* @return decimal 
     	*/
     	public function getMontant() {
       		return $this->montant;
     	}
		/**
     	* Get saisie
     	*
     	* @return MyCompany\MyProject\AppBundle\Entity\FraudeSaisie 
     	*/
     	public function getSaisie() {
       		return $this->saisie;
     	}
		/**
     	* Get titre
     	*
     	* @return string 
     	*/
     	public function getTitre() {
       		return $this->titre;
     	}
		/**
     	* Get typologie
     	*
     	* @return MyCompany\MyProject\AppBundle\Entity\FraudeTypologie 
     	*/
     	public function getTypologie() {
       		return $this->typologie;
     	}
		/**
     	* Get dateEvt
     	*
     	* @return datetime 
     	*/
     	public function getDateEvt() {
       		return $this->dateEvt;
     	}
		/**
     	* Get description
     	*
     	* @return string 
     	*/
     	public function getDescription() {
       		return $this->description;
     	}
		/**
     	* Set dateEvt
     	*
     	* @param datetime $dateEvt
     	*/ 
     	public function setDateEvt($dateEvt) {
			$this->dateEvt=$dateEvt;  
  	 	}	
		/**
     	* Set description
     	*
     	* @param string $description
     	*/ 
     	public function setDescription($description) {
			$this->description=$description;  
  	 	}	
		/**
     	* Set montant
     	*
     	* @param decimal $montant
     	*/ 
     	public function setMontant($montant) {
			$this->montant=$montant;  
  	 	}	
		/**
     	* Set titre
     	*
     	* @param string $titre
     	*/ 
     	public function setTitre($titre) {
			$this->titre=$titre;  
  	 	}	
		/**
     	* Set typologie
     	*
     	* @param MyCompany\MyProject\AppBundle\Entity\FraudeTypologie $typologie
     	*/ 
     	public function setTypologie(\MyCompany\MyProject\AppBundle\Entity\FraudeTypologie $typologie) {
       		$this->typologie=$typologie;  
  	 	}
		// Object validation function (see Resources/config/validation.yml)
		public function isDateEvtValid() {
			$rc = true; $errorMgr = $this; $errorMsg = ''; 
			$this->validDateEvt = true;
			/*==============START OF VALIDATION RULE====================*/ 
			
			/*==============END OF VALIDATION RULE======================*/
			if(!$rc) {
				$errorMgr->setError($errorMsg);
				$this->validDateEvt = false;
				return $rc;
			}
		}
		// Object validation function (see Resources/config/validation.yml)
		public function isDescriptionValid() {
			$rc = true; $errorMgr = $this; $errorMsg = ''; 
			$this->validDescription = true;
			/*==============START OF VALIDATION RULE====================*/ 
			
			/*==============END OF VALIDATION RULE======================*/
			if(!$rc) {
				$errorMgr->setError($errorMsg);
				$this->validDescription = false;
				return $rc;
			}
		}
		// Object validation function (see Resources/config/validation.yml)
		public function isMontantValid() {
			$rc = true; $errorMgr = $this; $errorMsg = ''; 
			$this->validMontant = true;
			/*==============START OF VALIDATION RULE====================*/ 
			
			/*==============END OF VALIDATION RULE======================*/
			if(!$rc) {
				$errorMgr->setError($errorMsg);
				$this->validMontant = false;
				return $rc;
			}
		}
		// Object validation function (see Resources/config/validation.yml)
		public function isSaisieValid() {
			$rc = true; $errorMgr = $this; $errorMsg = ''; 
			$this->validSaisie = true;
			/*==============START OF VALIDATION RULE====================*/ 
			
			/*==============END OF VALIDATION RULE======================*/
			if(!$rc) {
				$errorMgr->setError($errorMsg);
				$this->validSaisie = false;
				return $rc;
			}
		}
		// Object validation function (see Resources/config/validation.yml)
		public function isTitreValid() {
			$rc = true; $errorMgr = $this; $errorMsg = ''; 
			$this->validTitre = true;
			/*==============START OF VALIDATION RULE====================*/ 
			
			/*==============END OF VALIDATION RULE======================*/
			if(!$rc) {
				$errorMgr->setError($errorMsg);
				$this->validTitre = false;
				return $rc;
			}
		}
		// Object validation function (see Resources/config/validation.yml)
		public function isToStringValid() {
			$rc = true; $errorMgr = $this; $errorMsg = ''; 
			$this->validToString = true;
			/*==============START OF VALIDATION RULE====================*/ 
			
			/*==============END OF VALIDATION RULE======================*/
			if(!$rc) {
				$errorMgr->setError($errorMsg);
				$this->validToString = false;
				return $rc;
			}
		}
		// Object validation function (see Resources/config/validation.yml)
		public function isTypologieValid() {
			$rc = true; $errorMgr = $this; $errorMsg = ''; 
			$this->validTypologie = true;
			/*==============START OF VALIDATION RULE====================*/ 
			
			/*==============END OF VALIDATION RULE======================*/
			if(!$rc) {
				$errorMgr->setError($errorMsg);
				$this->validTypologie = false;
				return $rc;
			}
		}
		public function setError($error) {
			$this->error = $error;
		}
		public function getError() {
			return $this->error;
		}
   }
?>
