<?php
	// Entity class generated automatically by MDA process
	namespace MyCompany\MyProject\AppBundle\Entity;

	use Doctrine\ORM\Mapping as ORM;
	use JMS\SecurityExtraBundle\Annotation\Secure;
	use Symfony\Component\Validator\Constraints as Assert;
	use Symfony\Bridge\Doctrine\Validator\Constraints as DoctrineAssert;
	use Doctrine\Common\Collections\ArrayCollection;

	/**
 	* MyCompany\MyProject\AppBundle\Entity\PamPeriode
 	*
 	* @ORM\Table(name="pam_periode")
 	* @ORM\Entity(repositoryClass="MyCompany\MyProject\AppBundle\Repository\PamPeriodeRepository")
	* */
   	class PamPeriode
	{	
		// MDA Generated variables (used for internal entity management)
		private $error = '';
		public $validAnnee = true;
		public $validName = true;
		public $validSemestre = true;

		/**
     	* @var bigint $id
     	*
     	* @ORM\Column(name="id", type="bigint", nullable=false)
     	* @ORM\Id
     	* @ORM\GeneratedValue(strategy="IDENTITY")
     	*/
    	private $id;
		/**
     	* @var Annee
     	* @ORM\ManyToOne(targetEntity="PamAnnee")
     	* @ORM\JoinColumns({
     	* @ORM\JoinColumn(name="annee_id", referencedColumnName="id", unique=true)
     	* })
		*/
		private $annee;		
		/**
     	* @var string $name
     	*
     	*/
    	private $name;
		/**
     	* @var Semestre
     	* @ORM\ManyToOne(targetEntity="PamSemestre")
     	* @ORM\JoinColumns({
     	* @ORM\JoinColumn(name="semestre_id", referencedColumnName="id", unique=true)
     	* })
		*/
		private $semestre;		
		public function __construct()
    	{
		}
	
		/**
     	* Get id
     	*
     	* @return bigint 
     	*/
    	public function getId()
    	{
        	return $this->id;
    	}
    	public function setId($id)
    	{
        	$this->id = $id;
    	}
		/**
     	* Get Name 
		* by Id (automatic get generated by Symfony
     	*        when form display choice list)
     	* @return string
     	*/		
		public function __toString() {
			return $this->getName();
		}
		/**
     	* Get annee
     	*
     	* @return MyCompany\MyProject\AppBundle\Entity\PamAnnee 
     	*/
     	public function getAnnee() {
       		return $this->annee;
     	}
		/**
     	* Get name
     	*
     	* @return string 
     	*/
     	public function getName() {
			 $this->name = $this->annee->getName() . "_" . $this->semestre->getName();
       		return $this->name;
     	}
		/**
     	* Get semestre
     	*
     	* @return MyCompany\MyProject\AppBundle\Entity\PamSemestre 
     	*/
     	public function getSemestre() {
       		return $this->semestre;
     	}
		/**
     	* Set annee
     	*
     	* @param MyCompany\MyProject\AppBundle\Entity\PamAnnee $annee
     	*/ 
     	public function setAnnee(\MyCompany\MyProject\AppBundle\Entity\PamAnnee $annee) {
       		$this->annee=$annee;  
  	 	}
		/**
     	* Set semestre
     	*
     	* @param MyCompany\MyProject\AppBundle\Entity\PamSemestre $semestre
     	*/ 
     	public function setSemestre(\MyCompany\MyProject\AppBundle\Entity\PamSemestre $semestre) {
       		$this->semestre=$semestre;  
  	 	}
		// Object validation function (see Resources/config/validation.yml)
		public function isAnneeValid() {
			$rc = true; $errorMgr = $this; $errorMsg = ''; 
			$this->validAnnee = true;
			/*==============START OF VALIDATION RULE====================*/ 
			
			/*==============END OF VALIDATION RULE======================*/
			if(!$rc) {
				$errorMgr->setError($errorMsg);
				$this->validAnnee = false;
				return $rc;
			}
		}
		// Object validation function (see Resources/config/validation.yml)
		public function isNameValid() {
			$rc = true; $errorMgr = $this; $errorMsg = ''; 
			$this->validName = true;
			/*==============START OF VALIDATION RULE====================*/ 
			
			/*==============END OF VALIDATION RULE======================*/
			if(!$rc) {
				$errorMgr->setError($errorMsg);
				$this->validName = false;
				return $rc;
			}
		}
		// Object validation function (see Resources/config/validation.yml)
		public function isSemestreValid() {
			$rc = true; $errorMgr = $this; $errorMsg = ''; 
			$this->validSemestre = true;
			/*==============START OF VALIDATION RULE====================*/ 
			
			/*==============END OF VALIDATION RULE======================*/
			if(!$rc) {
				$errorMgr->setError($errorMsg);
				$this->validSemestre = false;
				return $rc;
			}
		}
		public function setError($error) {
			$this->error = $error;
		}
		public function getError() {
			return $this->error;
		}
   }
?>
