<?php
	// Entity class generated automatically by MDA process
	namespace MyCompany\MyProject\AppBundle\Entity;

	use Doctrine\ORM\Mapping as ORM;
	use JMS\SecurityExtraBundle\Annotation\Secure;
	use Symfony\Component\Validator\Constraints as Assert;
	use Symfony\Bridge\Doctrine\Validator\Constraints as DoctrineAssert;
	use Doctrine\Common\Collections\ArrayCollection;

	/**
 	* MyCompany\MyProject\AppBundle\Entity\PamSysteme
 	*
 	* @ORM\Table(name="pam_systeme")
 	* @ORM\Entity(repositoryClass="MyCompany\MyProject\AppBundle\Repository\PamSystemeRepository")
	* */
   	class PamSysteme
	{	
		// MDA Generated variables (used for internal entity management)
		private $error = '';
		public $validAcquisition = true;
		public $validFiliale = true;
		public $validName = true;
		public $validScope = true;

		/**
     	* @var bigint $id
     	*
     	* @ORM\Column(name="id", type="bigint", nullable=false)
     	* @ORM\Id
     	* @ORM\GeneratedValue(strategy="IDENTITY")
     	*/
    	private $id;
		/**
     	* @var Acquisition
     	* @ORM\ManyToOne(targetEntity="PamAcquisition")
     	* @ORM\JoinColumns({
     	* @ORM\JoinColumn(name="acquisition_id", referencedColumnName="id", unique=true)
     	* })
		*/
		private $acquisition;		
		/**
     	* @var Filiale
     	* @ORM\ManyToOne(targetEntity="PamFiliale")
     	* @ORM\JoinColumns({
     	* @ORM\JoinColumn(name="filiale_id", referencedColumnName="id", unique=true)
     	* })
		*/
		private $filiale;		
		/**
     	* @var string $name
     	*
     	*/
    	private $name;
		/**
     	* @var pamfiliale $scope
     	*
     	*/
    	private $scope;
		public function __construct()
    	{
		}
	
		/**
     	* Get id
     	*
     	* @return bigint 
     	*/
    	public function getId()
    	{
        	return $this->id;
    	}
    	public function setId($id)
    	{
        	$this->id = $id;
    	}
		/**
     	* Get Name 
		* by Id (automatic get generated by Symfony
     	*        when form display choice list)
     	* @return string
     	*/		
		public function __toString() {
			return $this->getName();
		}
		/**
     	* Get acquisition
     	*
     	* @return MyCompany\MyProject\AppBundle\Entity\PamAcquisition 
     	*/
     	public function getAcquisition() {
       		return $this->acquisition;
     	}
		/**
     	* Get scope
     	*
     	* @return pamfiliale 
     	*/
     	public function getScope() {
			$this->scope = $this->filiale->getName();
       		return $this->scope;
     	}
		/**
     	* Get filiale
     	*
     	* @return MyCompany\MyProject\AppBundle\Entity\PamFiliale 
     	*/
     	public function getFiliale() {
       		return $this->filiale;
     	}
		/**
     	* Get name
     	*
     	* @return string 
     	*/
     	public function getName() {
			 $this->name = $this->filiale->getName() . "_" .  $this->acquisition->getName();
       		return $this->name;
     	}
		/**
     	* Set acquisition
     	*
     	* @param MyCompany\MyProject\AppBundle\Entity\PamAcquisition $acquisition
     	*/ 
     	public function setAcquisition(\MyCompany\MyProject\AppBundle\Entity\PamAcquisition $acquisition) {
       		$this->acquisition=$acquisition;  
  	 	}
		/**
     	* Set filiale
     	*
     	* @param MyCompany\MyProject\AppBundle\Entity\PamFiliale $filiale
     	*/ 
     	public function setFiliale(\MyCompany\MyProject\AppBundle\Entity\PamFiliale $filiale) {
       		$this->filiale=$filiale;  
  	 	}
		// Object validation function (see Resources/config/validation.yml)
		public function isAcquisitionValid() {
			$rc = true; $errorMgr = $this; $errorMsg = ''; 
			$this->validAcquisition = true;
			/*==============START OF VALIDATION RULE====================*/ 
			
			/*==============END OF VALIDATION RULE======================*/
			if(!$rc) {
				$errorMgr->setError($errorMsg);
				$this->validAcquisition = false;
				return $rc;
			}
		}
		// Object validation function (see Resources/config/validation.yml)
		public function isFilialeValid() {
			$rc = true; $errorMgr = $this; $errorMsg = ''; 
			$this->validFiliale = true;
			/*==============START OF VALIDATION RULE====================*/ 
			
			/*==============END OF VALIDATION RULE======================*/
			if(!$rc) {
				$errorMgr->setError($errorMsg);
				$this->validFiliale = false;
				return $rc;
			}
		}
		// Object validation function (see Resources/config/validation.yml)
		public function isNameValid() {
			$rc = true; $errorMgr = $this; $errorMsg = ''; 
			$this->validName = true;
			/*==============START OF VALIDATION RULE====================*/ 
			
			/*==============END OF VALIDATION RULE======================*/
			if(!$rc) {
				$errorMgr->setError($errorMsg);
				$this->validName = false;
				return $rc;
			}
		}
		// Object validation function (see Resources/config/validation.yml)
		public function isScopeValid() {
			$rc = true; $errorMgr = $this; $errorMsg = ''; 
			$this->validScope = true;
			/*==============START OF VALIDATION RULE====================*/ 
			
			/*==============END OF VALIDATION RULE======================*/
			if(!$rc) {
				$errorMgr->setError($errorMsg);
				$this->validScope = false;
				return $rc;
			}
		}
		public function setError($error) {
			$this->error = $error;
		}
		public function getError() {
			return $this->error;
		}
   }
?>
