# Security class generated automatically by MDA process
# MyCompany\MyProject\SysBundle\Resources\config\security
security: 
    firewalls: 
        secured_area:
            logout:
                path: /logout
                target: /login
            form_login: ~
            pattern: ^/
            anonymous: ~

    access_control:
          - { path: ^/admin, roles: ROLE_ADMIN }  
          - { path: ^/admin/users, roles: ROLE_SUPER_ADMIN }  
          - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }  

    providers:
        chain_provider:
            providers: [in_memory, user_db]
        user_db:
            entity: { class: MyCompany\MyProject\SysBundle\Entity\AdminUser, property: username } 
        in_memory: 
            users: 
                ryan: { password: ryanpass, roles: 'ROLE_USER' } 
                admin: { password: kitten, roles: 'ROLE_ADMIN' } 

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        MyCompany\MyProject\SysBundle\Entity\AdminUser: sha512

    role_hierarchy: 
        ROLE_ADMAPP_ANY_ANY: [ROLE_LECTEUR_ANY_ANY, ROLE_MODERATEUR]
        ROLE_ADMIN: [ROLE_BASIC, ROLE_LECTEUR, ROLE_REDACTEUR, ROLE_MODERATEUR, ROLE_SYS_MAIN, ROLE_APP_SECTION0]
        ROLE_ANY_ANY_ANY: [ROLE_ADMIN, ROLE_DOMAINS]
        ROLE_APP_PAGE001: [ROLE_APP_PAGE0010, ROLE_APP_PAGE0011, ROLE_APP_PAGE0012, ROLE_APP_PAGE0013, ROLE_APP_PAGE0014, ROLE_APP_PAGE0015, ROLE_APP_PAGE0016, ROLE_APP_PAGE0017]
        ROLE_APP_PAGE002: [ROLE_APP_PAGE0020]
        ROLE_APP_SECTION0: [ROLE_APP_PAGE001, ROLE_APP_PAGE002, ROLE_APP_PAGE003, ROLE_APP_PAGE004]
        ROLE_APP_SECTION1: [ROLE_APP_PAGE101, ROLE_APP_PAGE102, ROLE_APP_PAGE103, ROLE_APP_PAGE104]
        ROLE_APP_SECTION2: [ROLE_APP_PAGE201, ROLE_APP_PAGE202, ROLE_APP_PAGE203, ROLE_APP_PAGE204]
        ROLE_APP_SECTION3: [ROLE_APP_PAGE301, ROLE_APP_PAGE302, ROLE_APP_PAGE303, ROLE_APP_PAGE304]
        ROLE_APP_SECTION4: [ROLE_APP_PAGE401, ROLE_APP_PAGE402, ROLE_APP_PAGE403, ROLE_APP_PAGE404]
        ROLE_APP_SECTIONS: [ROLE_APP_SECTION1, ROLE_APP_SECTION2, ROLE_APP_SECTION3, ROLE_APP_SECTION4]
        ROLE_BASIC: [ROLE_MESSAGE, ROLE_WELCOME, ROLE_MENU, ROLE_APP_PAM ]
        ROLE_CREATEUR: [ ROLE_NEW, ROLE_ENTER, ROLE_CREATE]
        ROLE_DOMAINS: [ROLE_FRAUDE, ROLE_EVENT]
        ROLE_EDITEUR: [ROLE_EDIT, ROLE_UPDATE, ROLE_SAVE]
        ROLE_FRAUDE: [ROLE_APP_PAM, ROLE_APP_SECTION1]
        ROLE_LECTEUR: [ROLE_INDEX, ROLE_SHOW]
        ROLE_LECTEUR_ANY_ANY: [ROLE_BASIC, ROLE_LECTEUR, ROLE_DOMAINS]
        ROLE_LECTEUR_ANY_BDP: [ROLE_LECTEUR_ANY_FILIALE]
        ROLE_LECTEUR_ANY_BRD: [ROLE_LECTEUR_ANY_FILIALE]
        ROLE_LECTEUR_ANY_FILIALE: [ROLE_BASIC, ROLE_LECTEUR, ROLE_DOMAINS]
        ROLE_LECTEUR_ANY_NSGB: [ROLE_LECTEUR_ANY_FILIALE]
        ROLE_LECTEUR_ANY_SGBS: [ROLE_LECTEUR_ANY_FILIALE]
        ROLE_MANAGER_ANY_BDP: [ROLE_MANAGER_ANY_FILIALE]
        ROLE_MANAGER_ANY_BRD: [ROLE_MANAGER_ANY_FILIALE]
        ROLE_MANAGER_ANY_FILIALE: [ROLE_BASIC, ROLE_LECTEUR, ROLE_EDITEUR, ROLE_FRAUDE, ROLE_EVENT]
        ROLE_MANAGER_ANY_NSGB: [ROLE_MANAGER_ANY_FILIALE]
        ROLE_MANAGER_ANY_SGBS: [ROLE_MANAGER_ANY_FILIALE]
        ROLE_MENU: [ROLE_INIT, ROLE_T, ROLE_SYS_APP, ROLE_SYS_LOGOUT]
        ROLE_MODERATEUR: [ROLE_DELETE]
        ROLE_REDACTEUR: [ROLE_EDIT, ROLE_NEW, ROLE_CREATE, ROLE_UPDATE, ROLE_SAVE]
        ROLE_REDACTEUR_FRAUDE_ANY: [ROLE_BASIC, ROLE_LECTEUR, ROLE_CREATEUR, ROLE_FRAUDE, ROLE_EVENT]
        ROLE_REDACTEUR_FRAUDE_BDP: [ROLE_REDACTEUR_FRAUDE_FILIALE]
        ROLE_REDACTEUR_FRAUDE_BRD: [ROLE_REDACTEUR_FRAUDE_FILIALE]
        ROLE_REDACTEUR_FRAUDE_FILIALE: [ROLE_BASIC, ROLE_LECTEUR, ROLE_CREATEUR, ROLE_FRAUDE, ROLE_EVENT]
        ROLE_REDACTEUR_FRAUDE_NSGB: [ROLE_REDACTEUR_FRAUDE_FILIALE]
        ROLE_REDACTEUR_FRAUDE_SGBS: [ROLE_REDACTEUR_FRAUDE_FILIALE]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SYSADM_ANY_ANY: [ROLE_ADMIN]
        ROLE_SYS_MAIN: [ROLE_SYS_SECTIONS]
        ROLE_SYS_SECTION0: [ROLE_SYS_PAGE001, ROLE_SYS_PAGE002, ROLE_SYS_PAGE003, ROLE_SYS_PAGE004]
        ROLE_SYS_SECTION1: [ROLE_SYS_PAGE101, ROLE_SYS_PAGE102, ROLE_SYS_PAGE103, ROLE_SYS_PAGE104]
        ROLE_SYS_SECTION2: [ROLE_SYS_PAGE201, ROLE_SYS_PAGE202, ROLE_SYS_PAGE203, ROLE_SYS_PAGE204]
        ROLE_SYS_SECTION3: [ROLE_SYS_PAGE301, ROLE_SYS_PAGE302, ROLE_SYS_PAGE303, ROLE_SYS_PAGE304]
        ROLE_SYS_SECTION4: [ROLE_SYS_PAGE401, ROLE_SYS_PAGE402, ROLE_SYS_PAGE403, ROLE_SYS_PAGE404]
        ROLE_SYS_SECTIONS: [ROLE_SYS_SECTION0, ROLE_SYS_SECTION1, ROLE_SYS_SECTION2, ROLE_SYS_SECTION3, ROLE_SYS_SECTION4]
